[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
network = { path = "../network" }
storage = { path = "../storage" }
ionian_spec = { path = "../../common/spec" }
task_executor = { path = "../../common/task_executor" }
contract-interface = { path = "../../common/contract-interface" }
ethereum-types = "0.13"
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1.35"
blake2 = "0.10"
tiny-keccak = {version="2.0",features = ["keccak"]}
rand = "^0.8"
ethers = { git = "https://github.com/k-huetsch/ethers-rs.git", branch="ionian-dev", features = ["ws", "rustls", "abigen"] }
lazy_static = "1.4"
async-trait = "0.1.56"
shared_types = { path = "../shared_types" }
